/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TDA_Polinomios;
import TDA_Polinomios.Polinomio;
import TDA_Polinomios.Monomio;
public class PolinomioView extends javax.swing.JFrame {

    Polinomio A;
    Polinomio B;
    public PolinomioView() {
        initComponents();
        A=new Polinomio(5);
        B=new Polinomio(5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        CBx1 = new javax.swing.JComboBox<>();
        TxtCoef = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtExp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PrimerPolinomio = new javax.swing.JTextField();
        SegundoPolinomio = new javax.swing.JTextField();
        PrimerPolinomioSelect = new javax.swing.JRadioButton();
        SegundoPolinomioSelect = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Resultado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Sumar = new javax.swing.JButton();
        Multiplicar = new javax.swing.JButton();
        Restar = new javax.swing.JButton();
        EvaluarButton = new javax.swing.JButton();
        ObtenerMonomioButton = new javax.swing.JButton();
        EvaluarTextField = new javax.swing.JTextField();
        GradoTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(540, 222));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CBx1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));
        getContentPane().add(CBx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 50, -1));
        getContentPane().add(TxtCoef, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 41, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("TDA Polinomio");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));
        getContentPane().add(TxtExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 42, -1));

        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 80, -1));

        jLabel3.setText("Coef");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 80, 30, -1));

        jLabel4.setText("Exp");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 20, -1));

        PrimerPolinomio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimerPolinomioActionPerformed(evt);
            }
        });
        getContentPane().add(PrimerPolinomio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 210, -1));
        getContentPane().add(SegundoPolinomio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 210, -1));

        buttonGroup1.add(PrimerPolinomioSelect);
        PrimerPolinomioSelect.setText("1º P(x)");
        PrimerPolinomioSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimerPolinomioSelectActionPerformed(evt);
            }
        });
        getContentPane().add(PrimerPolinomioSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        buttonGroup1.add(SegundoPolinomioSelect);
        SegundoPolinomioSelect.setText("2º P(x)");
        SegundoPolinomioSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegundoPolinomioSelectActionPerformed(evt);
            }
        });
        getContentPane().add(SegundoPolinomioSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        jLabel2.setText("P1(X)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel5.setText("P2(X)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        Resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoActionPerformed(evt);
            }
        });
        getContentPane().add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 210, -1));

        jLabel6.setText("Resultado");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 60, 20));

        Sumar.setText("Sumar");
        Sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumarActionPerformed(evt);
            }
        });
        getContentPane().add(Sumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 90, -1));

        Multiplicar.setText("Multiplicar");
        Multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(Multiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 90, -1));

        Restar.setText("Restar");
        Restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestarActionPerformed(evt);
            }
        });
        getContentPane().add(Restar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 90, -1));

        EvaluarButton.setText("Evaluar X");
        EvaluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvaluarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EvaluarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 130, -1));

        ObtenerMonomioButton.setText("Obtener Monomio");
        ObtenerMonomioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObtenerMonomioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ObtenerMonomioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 130, -1));

        EvaluarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvaluarTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(EvaluarTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 50, -1));
        getContentPane().add(GradoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 50, -1));

        jLabel7.setText("Grado");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        jLabel8.setText("Valor de X");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int Coef = Integer.parseInt(TxtCoef.getText());
        int Exp = Integer.parseInt(TxtExp.getText());
        String signo = CBx1.getSelectedItem().toString();
        char Signo = signo.charAt(0);

        if (PrimerPolinomioSelect.isSelected()) {
            A.insertar(Signo, Coef, Exp);
            PrimerPolinomio.setText(A.toString());
        } else if (SegundoPolinomioSelect.isSelected()) {
            B.insertar(Signo, Coef, Exp);
            SegundoPolinomio.setText(B.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PrimerPolinomioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimerPolinomioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrimerPolinomioActionPerformed

    private void SegundoPolinomioSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundoPolinomioSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SegundoPolinomioSelectActionPerformed

    private void PrimerPolinomioSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimerPolinomioSelectActionPerformed

    }//GEN-LAST:event_PrimerPolinomioSelectActionPerformed

    private void ResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoActionPerformed

    private void SumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumarActionPerformed
        Polinomio resultado = A.sumar(B);
        Resultado.setText(resultado.toString());
    }//GEN-LAST:event_SumarActionPerformed

    private void RestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestarActionPerformed
        Polinomio resultado = A.restar(B);
        Resultado.setText(resultado.toString());
    }//GEN-LAST:event_RestarActionPerformed

    private void MultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicarActionPerformed
        Polinomio resultado = A.multiplicar(B);
        Resultado.setText(resultado.toString());
    }//GEN-LAST:event_MultiplicarActionPerformed

    private void EvaluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvaluarButtonActionPerformed
        try {
            double x = Double.parseDouble(EvaluarTextField.getText());
            double resultado = (PrimerPolinomioSelect.isSelected() ? A : B).evaluar(x);
            if (resultado == (long) resultado) {
                // El resultado es efectivamente un entero
                Resultado.setText(String.format("%d", (long) resultado));
            } else {
                // El resultado es un número con parte decimal
                Resultado.setText(String.format("%.2f", resultado));
            }
        } catch (NumberFormatException ex) {
            Resultado.setText("Entrada no válida");
        }
    }//GEN-LAST:event_EvaluarButtonActionPerformed

    private void ObtenerMonomioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObtenerMonomioButtonActionPerformed
        try {
            int grado = Integer.parseInt(GradoTextField.getText());
            Monomio m = (PrimerPolinomioSelect.isSelected() ? A : B).obtenerMonomio(grado);
            Resultado.setText(m != null ? m.toString() : "Monomio no encontrado");
        } catch (NumberFormatException ex) {
            Resultado.setText("Entrada no válida");
        }
    }//GEN-LAST:event_ObtenerMonomioButtonActionPerformed

    private void EvaluarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvaluarTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EvaluarTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolinomioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolinomioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolinomioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolinomioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolinomioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBx1;
    private javax.swing.JButton EvaluarButton;
    private javax.swing.JTextField EvaluarTextField;
    private javax.swing.JTextField GradoTextField;
    private javax.swing.JButton Multiplicar;
    private javax.swing.JButton ObtenerMonomioButton;
    private javax.swing.JTextField PrimerPolinomio;
    private javax.swing.JRadioButton PrimerPolinomioSelect;
    private javax.swing.JButton Restar;
    private javax.swing.JTextField Resultado;
    private javax.swing.JTextField SegundoPolinomio;
    private javax.swing.JRadioButton SegundoPolinomioSelect;
    private javax.swing.JButton Sumar;
    private javax.swing.JTextField TxtCoef;
    private javax.swing.JTextField TxtExp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
