/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TDA_Polynomials;
import TDA_Polynomials.Polynomial;
import TDA_Polynomials.Monomial;
public class PolynomialView extends javax.swing.JFrame {

    Polynomial A;
    Polynomial B;
    public PolynomialView() {
        initComponents();
        A=new Polynomial(5);
        B=new Polynomial(5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        CBx1 = new javax.swing.JComboBox<>();
        TxtCoef = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtExp = new javax.swing.JTextField();
        InsertButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FirstPolynomial = new javax.swing.JTextField();
        SecondPolynomial = new javax.swing.JTextField();
        FirstPolynomialSelect = new javax.swing.JRadioButton();
        SecondPolynomialSelect = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Result = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SumButton = new javax.swing.JButton();
        MultiplyButton = new javax.swing.JButton();
        SubtractButton = new javax.swing.JButton();
        EvaluateButton = new javax.swing.JButton();
        GetMonomialButton = new javax.swing.JButton();
        EvaluateTextField = new javax.swing.JTextField();
        GradeTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(540, 222));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CBx1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));
        getContentPane().add(CBx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 50, -1));
        getContentPane().add(TxtCoef, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 41, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("TDA Polinomio");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));
        getContentPane().add(TxtExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 42, -1));

        InsertButton.setText("Insertar");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });
        getContentPane().add(InsertButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 80, -1));

        jLabel3.setText("Coef");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 80, 30, -1));

        jLabel4.setText("Exp");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 20, -1));

        FirstPolynomial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstPolynomialActionPerformed(evt);
            }
        });
        getContentPane().add(FirstPolynomial, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 210, -1));
        getContentPane().add(SecondPolynomial, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 210, -1));

        buttonGroup1.add(FirstPolynomialSelect);
        FirstPolynomialSelect.setText("1º P(x)");
        FirstPolynomialSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstPolynomialSelectActionPerformed(evt);
            }
        });
        getContentPane().add(FirstPolynomialSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        buttonGroup1.add(SecondPolynomialSelect);
        SecondPolynomialSelect.setText("2º P(x)");
        SecondPolynomialSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondPolynomialSelectActionPerformed(evt);
            }
        });
        getContentPane().add(SecondPolynomialSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        jLabel2.setText("P1(X)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel5.setText("P2(X)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultActionPerformed(evt);
            }
        });
        getContentPane().add(Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 210, -1));

        jLabel6.setText("Resultado");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 60, 20));

        SumButton.setText("Sumar");
        SumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SumButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 90, -1));

        MultiplyButton.setText("Multiplicar");
        MultiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MultiplyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 90, -1));

        SubtractButton.setText("Restar");
        SubtractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtractButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SubtractButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 90, -1));

        EvaluateButton.setText("Evaluar X");
        EvaluateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvaluateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EvaluateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 130, -1));

        GetMonomialButton.setText("Obtener Monomio");
        GetMonomialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetMonomialButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GetMonomialButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 130, -1));

        EvaluateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvaluateTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(EvaluateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 50, -1));
        getContentPane().add(GradeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 50, -1));

        jLabel7.setText("Grado");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        jLabel8.setText("Valor de X");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        int Coef = Integer.parseInt(TxtCoef.getText());
        int Exp = Integer.parseInt(TxtExp.getText());
        String sign = CBx1.getSelectedItem().toString();
        char Sign = sign.charAt(0);

        if (FirstPolynomialSelect.isSelected()) {
            A.insert(Sign, Coef, Exp);
            FirstPolynomial.setText(A.toString());
        } else if (SecondPolynomialSelect.isSelected()) {
            B.insert(Sign, Coef, Exp);
            SecondPolynomial.setText(B.toString());
        }
    }//GEN-LAST:event_InsertButtonActionPerformed

    private void FirstPolynomialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstPolynomialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstPolynomialActionPerformed

    private void SecondPolynomialSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondPolynomialSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecondPolynomialSelectActionPerformed

    private void FirstPolynomialSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstPolynomialSelectActionPerformed

    }//GEN-LAST:event_FirstPolynomialSelectActionPerformed

    private void ResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultActionPerformed

    private void SumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumButtonActionPerformed
        Polynomial result = A.sum(B);
        Result.setText(result.toString());
    }//GEN-LAST:event_SumButtonActionPerformed

    private void SubtractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtractButtonActionPerformed
        Polynomial result = A.subtract(B);
        Result.setText(result.toString());
    }//GEN-LAST:event_SubtractButtonActionPerformed

    private void MultiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplyButtonActionPerformed
        Polynomial result = A.multiply(B);
        Result.setText(result.toString());
    }//GEN-LAST:event_MultiplyButtonActionPerformed

    private void EvaluateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvaluateButtonActionPerformed
        try {
            double x = Double.parseDouble(EvaluateTextField.getText());
            double result = (FirstPolynomialSelect.isSelected() ? A : B).evaluar(x);
            if (result == (long) result) {
                // El result es efectivamente un entero
                Result.setText(String.format("%d", (long) result));
            } else {
                // El result es un número con parte decimal
                Result.setText(String.format("%.2f", result));
            }
        } catch (NumberFormatException ex) {
            Result.setText("Entrada no válida");
        }
    }//GEN-LAST:event_EvaluateButtonActionPerformed

    private void GetMonomialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetMonomialButtonActionPerformed
        try {
            int grade = Integer.parseInt(GradeTextField.getText());
            Monomial m = (FirstPolynomialSelect.isSelected() ? A : B).getMonomial(grade);
            Result.setText(m != null ? m.toString() : "Monomio no encontrado");
        } catch (NumberFormatException ex) {
            Result.setText("Entrada no válida");
        }
    }//GEN-LAST:event_GetMonomialButtonActionPerformed

    private void EvaluateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvaluateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EvaluateTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolynomialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolynomialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolynomialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolynomialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolynomialView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBx1;
    private javax.swing.JButton EvaluateButton;
    private javax.swing.JTextField EvaluateTextField;
    private javax.swing.JTextField FirstPolynomial;
    private javax.swing.JRadioButton FirstPolynomialSelect;
    private javax.swing.JButton GetMonomialButton;
    private javax.swing.JTextField GradeTextField;
    private javax.swing.JButton InsertButton;
    private javax.swing.JButton MultiplyButton;
    private javax.swing.JTextField Result;
    private javax.swing.JTextField SecondPolynomial;
    private javax.swing.JRadioButton SecondPolynomialSelect;
    private javax.swing.JButton SubtractButton;
    private javax.swing.JButton SumButton;
    private javax.swing.JTextField TxtCoef;
    private javax.swing.JTextField TxtExp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
